module.exports = {
	setupFiles: ['./jest.setup.js'],
	transform: {
		'^.+\\.js?$': 'babel-jest',
		'.+\\.(css|styl|less|sass|scss)$': 'jest-css-modules-transform',
		'^.+\\.tsx?$': 'babel-jest',
		'^.+\\.mdx?$': '@storybook/addon-docs/jest-transform-mdx',
		'^.+\\.svg$': 'jest-svg-transformer',
		'^.+\\.(jpg|jpeg|png|gif|svg)$': 'jest-url-loader',
	},
	testRegex: ['(/src/.*\\.test)\\.(ts|js|tsx)$', 'storybook.test.js$'],
	collectCoverage: true,
	testResultsProcessor: 'jest-sonar-reporter',
	moduleNameMapper: {
		'^react($|/.+)': '<rootDir>/node_modules/react$1',
		'^@utils(.*)$': '<rootDir>/src/utils$1',
		'^@utils$': '<rootDir>/src/utils/index',
		'^@styles(.*)$': '<rootDir>/src/styles$1',
		'^@helper(.*)$': '<rootDir>/core/helper$1',
		'^@hooks(.*)$': '<rootDir>/src/hooks$1',
		'^@constants(.*)$': '<rootDir>/src/constants$1',
		'^@constants$': '<rootDir>/src/constants/index',
		'^@typings(.*)$': '<rootDir>/src/typings$1',
		'^@bc-checkout(.*)$': '<rootDir>/src/components$1',
		'^@uc(.*)$': '<rootDir>/src/components$1',
		'^@uc$': '<rootDir>/src/components/index',
		'\\.(css|less)$': 'identity-obj-proxy',
	},
	transformIgnorePatterns: ['<rootDir>/node_modules/'],
};
